image = "/PATH/TO/IMAGE.sqsh"

mounts = [...]

writable = true

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
FI_CXI_DEFAULT_TX_SIZE = "16384"
NCCL_NET_FORCE_FLUSH = "1"
FI_CXI_RDZV_GET_MIN = "0"
FI_CXI_SAFE_DEVMEM_COPY_THRESHOLD = "16777216"
NCCL_RAS_ENABLE = "0"
